name: signup_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  provider: ^4.2.0
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+3
  random_string: ^2.1.0
  font_awesome_flutter: ^8.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/UKG.jpg
    - assets/images/LKG.jpg
    - assets/images/final.PNG
    - assets/images/logo1-removebg-preview.png
    - assets/images/logo-removebg-preview.png
    - assets/images/3.jpg
    - assets/images/4.png
    - assets/images/5.jpg
    - assets/images/6.jpg
    - assets/images/7.jpg
    - assets/images/8.jpg
    - assets/images/9.jpg
    - assets/images/10.jpg
    - assets/images/11.PNG
    - assets/images/12.PNG
    - assets/images/budhha.jpg
    - assets/images/Math.jpg
    - assets/images/mental Ability.jpg
    - assets/images/Hindi.png
    - assets/images/General_Awareness.jpg
    - assets/images/EVS.jpg
    - assets/images/English.png
    - assets/images/Economics.jpg
    - assets/images/Science.jpg
    - assets/images/Fashion.jpeg
    - assets/images/Home Science.png
    - assets/images/LegalStudies.jpg
    - assets/images/Fine Art.jpg
    - assets/images/Physical Education.jpg
    - assets/images/Philosophy.jpg
    - assets/images/Psycology.jpg
    - assets/images/media studies.jpg
    - assets/images/business studies.jpg
    - assets/images/Geography.jpg
    - assets/images/Histroy.jpg
    - assets/images/Eiffle.jpg
    - assets/images/Germany.jpg
    - assets/images/sanskrit.jpg
    - assets/images/Biology.jpg
    - assets/images/chemistry.jpg
    - assets/images/physics.jpg
    - assets/images/computer.jpg
    - assets/images/social science.jpg
    - assets/images/Accountancy.jpg
    - assets/images/civics.jpg
    - assets/images/Political Science.jpg
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets\fonts\WorkSans-Black.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
